<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>A minimal managed PNG encoder/decoder built on LibImageQuant.Net.Core for producing quantized, palettized PNGs.</Description>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CRC.Fast.Net" Version="1.1.0" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
		<PackageReference Include="SpanDex" Version="1.0.2" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.9.0-beta.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ErrorProne.NET.Structs" Version="0.6.1-beta.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\LibImageQuant.Net.Core\LibImageQuant.Net.Core.csproj" />
	</ItemGroup>
</Project>
